export const buyNowWebinarAttendanceData = {
  success: true,
  data: {
    REGISTERED: {
      count: 200,
      users: [
        {
          id: '3f7b8a12-e3c1-4d5-9f8a-7b6c5d43f2a',
          name: 'Sarah Williams',
          email: 'sarah.williams@example.com',
          profileImage: 'https://randomuser.me/api/portraits/women/2.jpg',
          attendedAt: new Date('2025-04-05T14:00:00.000Z'),
          stripeConnectId: null,
          callStatus: 'PENDING' as const,
        },
        {
          id: '4a8b9c13-f4d2-5e6-0a9b-8c7d6e54g3b',
          name: 'Michael Chen',
          email: 'michael.chen@example.com',
          profileImage: 'https://randomuser.me/api/portraits/men/32.jpg',
          attendedAt: new Date('2025-04-05T15:30:00.000Z'),
          stripeConnectId: null,
          callStatus: 'PENDING' as const,
        },
        {
          id: '5b9c0d14-g5e3-6f7-1b0c-9d8e7f65h4c',
          name: 'Emily Rodriguez',
          email: 'emily.rodriguez@example.com',
          profileImage: 'https://randomuser.me/api/portraits/women/44.jpg',
          attendedAt: new Date('2025-04-05T16:15:00.000Z'),
          stripeConnectId: null,
          callStatus: 'PENDING' as const,
        },
      ],
    },
    ATTENDED: {
      count: 150,
      users: [
        {
          id: '6c0d1e15-h6f4-7g8-2c1d-0e9f8g76i5d',
          name: 'David Thompson',
          email: 'david.thompson@example.com',
          profileImage: 'https://randomuser.me/api/portraits/men/52.jpg',
          attendedAt: new Date('2025-04-05T14:10:00.000Z'),
          stripeConnectId: null,
          callStatus: 'PENDING' as const,
        },
        {
          id: '7d1e2f16-i7g5-8h9-3d2e-1f0g9h87j6e',
          name: 'Jessica Martinez',
          email: 'jessica.martinez@example.com',
          profileImage: 'https://randomuser.me/api/portraits/women/68.jpg',
          attendedAt: new Date('2025-04-05T14:25:00.000Z'),
          stripeConnectId: null,
          callStatus: 'PENDING' as const,
        },
        {
          id: '8e2f3g17-j8h6-9i0-4e3f-2g1h0i98k7f',
          name: 'Robert Anderson',
          email: 'robert.anderson@example.com',
          profileImage: 'https://randomuser.me/api/portraits/men/75.jpg',
          attendedAt: new Date('2025-04-05T15:00:00.000Z'),
          stripeConnectId: null,
          callStatus: 'PENDING' as const,
        },
      ],
    },
    ADDED_TO_CART: {
      count: 80,
      users: [
        {
          id: '9f3g4h18-k9i7-0j1-5f4g-3h2i1j09l8g',
          name: 'Lisa Brown',
          email: 'lisa.brown@example.com',
          profileImage: 'https://randomuser.me/api/portraits/women/28.jpg',
          attendedAt: new Date('2025-04-05T14:45:00.000Z'),
          stripeConnectId: null,
          callStatus: 'PENDING' as const,
        },
        {
          id: '0g4h5i19-l0j8-1k2-6g5h-4i3j2k10m9h',
          name: 'James Wilson',
          email: 'james.wilson@example.com',
          profileImage: 'https://randomuser.me/api/portraits/men/62.jpg',
          attendedAt: new Date('2025-04-05T15:20:00.000Z'),
          stripeConnectId: null,
          callStatus: 'InProgress' as const,
        },
        {
          id: '1h5i6j20-m1k9-2l3-7h6i-5j4k3l11n0i',
          name: 'Amanda Taylor',
          email: 'amanda.taylor@example.com',
          profileImage: 'https://randomuser.me/api/portraits/women/35.jpg',
          attendedAt: new Date('2025-04-05T15:50:00.000Z'),
          stripeConnectId: null,
          callStatus: 'PENDING' as const,
        },
      ],
    },
    FOLLOW_UP: {
      count: 45,
      users: [
        {
          id: '2i6j7k21-n2l0-3m4-8i7j-6k5l4m12o1j',
          name: 'Christopher Lee',
          email: 'christopher.lee@example.com',
          profileImage: 'https://randomuser.me/api/portraits/men/42.jpg',
          attendedAt: new Date('2025-04-05T14:30:00.000Z'),
          stripeConnectId: null,
          callStatus: 'InProgress' as const,
        },
        {
          id: '3j7k8l22-o3m1-4n5-9j8k-7l6m5n13p2k',
          name: 'Michelle Garcia',
          email: 'michelle.garcia@example.com',
          profileImage: 'https://randomuser.me/api/portraits/women/51.jpg',
          attendedAt: new Date('2025-04-05T15:05:00.000Z'),
          stripeConnectId: null,
          callStatus: 'COMPLETED' as const,
        },
      ],
    },
    CONVERTED: {
      count: 25,
      users: [
        {
          id: '4k8l9m23-p4n2-5o6-0k9l-8m7n6o14q3l',
          name: 'Daniel White',
          email: 'daniel.white@example.com',
          profileImage: 'https://randomuser.me/api/portraits/men/29.jpg',
          attendedAt: new Date('2025-04-05T14:15:00.000Z'),
          stripeConnectId: null,
          callStatus: 'COMPLETED' as const,
        },
        {
          id: '5l9m0n24-q5o3-6p7-1l0m-9n8o7p15r4m',
          name: 'Nicole Harris',
          email: 'nicole.harris@example.com',
          profileImage: 'https://randomuser.me/api/portraits/women/63.jpg',
          attendedAt: new Date('2025-04-05T14:40:00.000Z'),
          stripeConnectId: null,
          callStatus: 'COMPLETED' as const,
        },
        {
          id: '6m0n1o25-r6p4-7q8-2m1n-0o9p8q16s5n',
          name: 'Kevin Jackson',
          email: 'kevin.jackson@example.com',
          profileImage: 'https://randomuser.me/api/portraits/men/48.jpg',
          attendedAt: new Date('2025-04-05T15:15:00.000Z'),
          stripeConnectId: null,
          callStatus: 'COMPLETED' as const,
        },
      ],
    },
  },
  webinarTags: ['Hot Lead', 'VIP', 'Enterprise', 'Starter'],
}